// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import ExampleComponentController from "./../../../app/components/example_component/example_component_controller"
application.register("example", ExampleComponentController)


import HelloController from "./hello_controller"
application.register("hello", HelloController)
