# frozen_string_literal: true

require 'stimulus/manifest'

namespace :stimulus do
  namespace :manifest do
    task display: :environment do
      components_manifest = Stimulus::Manifest.generate_from(Rails.root.join('app/components'))
      controllers_manifest = Stimulus::Manifest.generate_from(Rails.root.join('app/javascript/controllers'))

      puts 'Components:'
      puts components_manifest
      puts
      puts 'Controllers:'
      puts controllers_manifest
    end

    task update: :environment do
      components_manifest = Stimulus::Manifest.generate_from(Rails.root.join('app/components'))
      controllers_manifest = Stimulus::Manifest.generate_from(Rails.root.join('app/javascript/controllers'))

      Rails.root.join('app/javascript/controllers/index.js').open('w+') do |index|
        index.puts '// This file is auto-generated by ./bin/rails stimulus:manifest:update'
        index.puts '// Run that command whenever you add a new controller or create them with'
        index.puts '// ./bin/rails generate stimulus controllerName'
        index.puts
        index.puts %(import { application } from "./application")
        index.puts components_manifest
        index.puts controllers_manifest
      end
    end
  end
end
