require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "app/assets/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "db/*"
    - "public/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/environments/development.rb"

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
