name: "CI with tests and linters"
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
  lint:
    name: "Linters and security audit"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop

      - name: ERB lint
        run: bundle exec erblint --lint-all

      - name: Security audit application code
        run: bundle exec brakeman

      - name: Check zeitwerk compatibility
        run: bundle exec rails zeitwerk:check
